---
- name: reboot machine
  hosts: all
  become: yes
  tasks:
  - name: check if system reboot is required
    become: true
    stat:
      path: /var/run/reboot-required
    register: reboot_required

  - name: Reboot the box if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required.stat.exists